### ISSUE TITLE
Flash ATMega168 chips

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/FortRebel#21]
We need flashed chips to send to Thonk:
50x Stoicheia
25x Logoi
25x Klasmata
(in labelled tubes)

Plus some spares to send to Alex4 for repairs: 2 each (individually labelled).

The programming ZIF socket has a header for an FTDI cable, to allow two-in-one programming.

**Comment by padski** [comment]
Stocheias & Logois & 6 extra done, awaiting more chips

**Comment by padski** [comment]
Done
