### ISSUE TITLE
Create colour coded placement sheets

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/FortRebel#22]
Electronic versions, for Stoicheia, Logoi and Klasmata.

**Comment by pingdynasty** [comment]
Should fit on one sheet with a colour-coded BOM, based on e.g.
https://docs.google.com/spreadsheets/d/1sq-qwEy1HwATB8ggEBUWu5q8Kma4ZveZFwoUYGh30KY/edit#gid=0

**Comment by padski** [comment]
Done, saved in respective /drawings/ folder
