### ISSUE TITLE
Prepare shipment for Thonk

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/FortRebel#23]
Kits for
- 50 Stoicheia
- 25 Logoi
- 25 Klasmata

for each:
- programmed MCU
- panel
- pcb (kit version)

Kit pcb's all have the thonkiconn jack. Awaiting delivery of Klasmata and Logoi pcb's.

**Comment by padski** [comment]
MCUs Done

**Comment by pingdynasty** [comment]
Stoicheia pcb's arrived today, pls pack all parts into a suitable box.

**Comment by padski** [comment]
Done

**Comment by pingdynasty** [comment]
Thonk have returned all but 11 Stoicheia PCBs.
Replacement PCBs have arrived from Seeed.
Prepare a parcel with the new PCBs to ship back to Thonk on the 25/7.

**Comment by padski** [comment]
Done, packaged 25 Logoi, 25 Klasmata, 40 Stoicheia
