### ISSUE TITLE
Build and test rectifier circuit

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/FortRebel#25]
Build the dual half-wave rectifier circuit on vero or breadboard to test it works before ordering pcb's.

Circuit is in `PowerBoard/schematics/RectifierBoard.sch`

Use the 2 2200uF caps that we have and test with an active bus board (PowerBoard). Should be able to draw at least 250mA on each 15v rail without loosing regulation.

**Comment by pingdynasty** [comment]
ie test with 48R load on +/-12v

**Comment by padski** [comment]
Done

**Comment by pingdynasty** [comment]
The LM317 datasheet [1] shows an improved ripple response when adding a 10uF cap from ADJ to gnd, ie bypass the reference voltage (C2 in Fig 13).

Test once RectifierBoard arrives.

[1] http://www.ti.com/lit/ds/symlink/lm317.pdf

**Comment by pingdynasty** [comment]
I've made and ordered a PTH version of PowerBoard, PowerKit, with C2 and rectifier onboard.

**Comment by pingdynasty** [comment]
Boards arrived, ordering big caps

**Comment by padski** [comment]
Done
