### ISSUE TITLE
Make 5v mini adaptors for OWL Modular

### ISSUE THREAD

**Issue by ghost** [RebelTechnology/FortRebel#26]
change to TO252 if possible

**Comment by pingdynasty** [comment]
- order pcb's
- order parts
- order stencil?
- assemble

**Comment by pingdynasty** [comment]
DPACK version arrived, 50 boards.
Paddy: build one and test pls!

**Comment by padski** [comment]
One built and soak testing

**Comment by pingdynasty** [comment]
Now for the remaining 49...

**Comment by padski** [comment]
Stencil Martin?

**Comment by pingdynasty** [comment]
stencil arrived, awaiting oven?

**Comment by padski** [comment]
Oven arrived!

**Comment by padski** [comment]
8 completed, 46 awaiting 8x2 fem headers

**Comment by pingdynasty** [comment]
Pls find suitable parts from Toby Electronics, Farnell, Rapid, RS

**Comment by padski** [comment]
Toby part added to shopping list

**Comment by padski** [comment]
Done, glitch, no parts required..
