### ISSUE TITLE
Lasercut panels for Schroff racks

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/FortRebel#28]
...awaiting frosted white 3mm perspex.

At the same time, cut some blank panels (pending outcome of #27).

**Comment by pingdynasty** [comment]
drawings are in RebelTechnology/PowerBoard/drawings

back and top panels: subrack.svg
blanks: blank6hp-inv.svg and blank4hp-inv.svg

If the inverted logos turn out shit, you could cut a couple of blanks with the logo on the front: blank6hp.svg and blank4hp.svg

**Comment by pingdynasty** [comment]
update: cut 1 each of top / back panel on long sheet of clear perspex, and 1 each of blank 4hp/6hp inverted and non-inverted on frosted perspex, plus any frosted orange blanks.

**Comment by padski** [comment]
Done
