### ISSUE TITLE
Build and test BalancedInput/Output Rev01

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/FortRebel#29]
Eagle files are in `RebelTechnology/PowerBoard/schematics/BalancedInputOutput.sch`

Build with sockets for chips : THAT1200 and THAT1646.
Use 220uF in C6 (or temporarily use 100uF if not available).

Test before populating neutrik sockets.

**Comment by pingdynasty** [comment]
Populate central 3-pin male header and 16-pin power header (not 2-pins)

**Comment by pingdynasty** [comment]
Leave out C1, C2, C3, R3. Ceramic film for 100n. C9 and C10 should be wima or similar if we have them in 10uF.

To test, connect an audio frequency signal, 1-10vpp, to the `out` pin. Check that balanced output is produced at OUT Tip and Ring.
Connect OUT Tip and Ring to IN Tip and Ring. Check that the same waveform is produced on the `in` pin.
Record the input and output gain factors and thresholds (max vpp without clipping).

**Comment by pingdynasty** [comment]
Actually C9 and C10 are supposed to be non-polarized electrolytic, which I don't think we have. Use wire links instead for now.

**Comment by padski** [comment]
Done, measurements sent to mars
