### ISSUE TITLE
Build and test PowerKit PTH

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/FortRebel#31]
There's a PowerBoard in PTH version with rectifier circuit.

Build with 4700uF rectifying caps and measure ripple (at +12, -12, +5)
- at 200mA
- at 250mA

and possibly higher if 250mA looks good (ripple less than 10%)

Eagle files are in RebelTechnology/PowerBoard/schematics/PowerKitPTH.sch / .brd

**Comment by padski** [comment]
Done
