### ISSUE TITLE
Build Klasmata and Logoi to test new PCBs

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/FortRebel#34]
Build 10 each (or so) of the new pcb's (new jacks) to see if there are issues.
Test boards first for obvious shorts:
- -12 / gnd
- +12 / gnd
- +5 / gnd
- +5 / +12
- toggle switches / gnd

seems sensible?

**Comment by padski** [comment]
Sounds good yes

**Comment by padski** [comment]
Done, all good :)
