### ISSUE TITLE
Prepare for workshops

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/FortRebel#35]
20x Stoicheia
10x Logoi
10x Klasmata
5x PowerKitPTH

pcb's need to be tested and parts collected.

**Comment by pingdynasty** [comment]
also need:
- power cables
- mounting screws and washers
- bags to take modules home in

**Comment by pingdynasty** [comment]
- soldering iron (antex)
- wire cutters
- solder wire
- avr programmer
- ftdi cable

**Comment by padski** [comment]
Done
