### ISSUE TITLE
Send Klasmata MCU to Luke Pankau

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/FortRebel#42]
Send a pre-programmed Klasmata MCU in small jiffy bag to Australia and tell me how much postage cost so I can send him a payment request. Address below.

lukepankau2002@msn.com

Hi Martin,

The red stripe of the power connector is facing downwards in the same orientation as all my other modules.

knobs are full ccw, triggers are being plugged into the bottom jack but no led action.

I'm certain I am doing everything right, and that the module is indeed faulty.

I purchased this module from equinoxoz quite some time ago, but have had abit of a falling out since with the owner 
...hes not talking to me anymore. :(

If you want to swing me a paypal money request for some cashola to pay for express postage I'm more than happy to do that.

my postal address is 

LUKE PANKAU
29 Nickol Rd
Karratha 
WA
6714
Australia

Cheers,
.Luke

**Comment by padski** [comment]
Postage cost: £3.30

**Comment by padski** [comment]
Done
