### ISSUE TITLE
Make a power supply for Spirit Folio mixer

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/FortRebel#48]
Use the Behringer AC adapter, and change either cable or connector end, or both.

**Comment by padski** [comment]
Awaiting connector from Rapid

**Comment by ghost** [comment]
http://www.blue-room.org.uk/index.php?showtopic=51571

On one, the PSU is marked up 19V - 0 - 19V AC 400mA
With no load this meters at about 23.4V - 0 - 23.4V AC

the other, older\* one says 17.1V - 0 - 17.1V AC 400mA
With no load this meters at about 21.3V - 0 - 21.3V AC

**Comment by ghost** [comment]
the centre pin is the common (0V)

**Comment by padski** [comment]
Done
