### ISSUE TITLE
Organize furniture collection

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/FortRebel#49]
9am Moorgate, Coleman st.

**Comment by padski** [comment]
Things to collect:
4 x 24" shelving + 20 shelves
6 x SBFI desks, 1500w x 870d x 710h
6 x SBFI desk pedestal, 3 drawer, 410w 560d x 590h
5 x Voko tambour unit 800w x 2100h x 440d grey / blue
6 x Chair, Girsberger 'Folio', task, 5 wheel, black, coat hanger on back (offer £20 each)
1 x Desk, height adjustable, grey (offer £30)

**Comment by pingdynasty** [comment]
to do:
- hire / borrow van
- rustle up volunteers
- put up do not park sign in driveway
- clear space in office to put the loot in
- bring tools to disassemble shelves

**Comment by padski** [comment]
Contact is Mike Turpin: 07778 445198
I'll require details of attendees, on shared Google Sheet.
Park in Coleman Street, as near as possible to the arched entry to Coleman Street Buildings Passage, just past Pret-a.Manger. Go to the post room entrance in the passageway and call Mike on his mobile, 07778 445198, and he will come down and let you in.

**Comment by ghost** [comment]
[anyvan-job-sheet-2617019.pdf](https://github.com/RebelTechnology/FortRebel/files/645/anyvan-job-sheet-2617019.pdf)

**Comment by ghost** [comment]
Collection address is assumed to be
74 Coleman Street
EC2R 5BN

**Comment by padski** [comment]
Done
