### ISSUE TITLE
Publish Video

### ISSUE THREAD

**Issue by enricobertelli** [RebelTechnology/FortRebel#54]
Create account on YouTube and decide tag-list

**Comment by enricobertelli** [comment]
rebeltechmodules@gmail.com

**Comment by pingdynasty** [comment]
Publicise on Twitter, Facebook, G+
Post on www.rebeltech.org, hoxtonowl.com

**Comment by enricobertelli** [comment]
All accounts up and running, please remember to use the bit.ly customised links every time you use it
