### ISSUE TITLE
Update rebeltech website

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/FortRebel#60]
Front page should include latest news, product photos, and twitter feed.

**Comment by enricobertelli** [comment]
Sam, the slider is ok, but it doesn't allow any hyperlinks (in free version).
It would be nice to be able to have that feature, as well as embedding videos.
Here's the code, directly from the plugin

[slider id='555' name='Homepage Slider' size='full']

**Comment by enricobertelli** [comment]
I've uploaded 3 images, called Slider_NAME, these are print screens from an iMovie I've created.
