### ISSUE TITLE
Promote to CDM and Synthopia

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/FortRebel#63]
Previous posts:
http://www.synthtopia.com/content/2015/07/28/owl-modular-programmable-eurorack-module-available-august-1/
http://www.synthtopia.com/content/2015/07/16/owl-open-source-dsp-platform-coming-to-eurorack/
http://createdigitalmusic.com/2013/06/a-stompbox-that-can-become-whatever-you-like-in-crowd-funded-owl/

**Comment by enricobertelli** [comment]
completed, awaiting CDM's response
