### ISSUE TITLE
Build OpenSound Rev04

### ISSUE THREAD

**Issue by ghost** [RebelTechnology/FortRebel#66]
Board and stencil have arrived.
- check BOM and stock
- update shopping list
- assemble

**Comment by ghost** [comment]
Rev04 should be built with yellow/green pushbutton, MultiMec 5GTH9352242, of which we have none.
rs 765-1551 £2.53 @100
farnell 2280490 £2.02 @100

**Comment by pingdynasty** [comment]
https://docs.google.com/spreadsheets/d/1iBVxUaHoj8_FYPgzlXVaghacCJn_tD5GXHwYD04l3XQ/edit#gid=1488444124

**Comment by padski** [comment]
10 done bar headers for photon

**Comment by padski** [comment]
6 now remain to be done, Photons required....
