### ISSUE TITLE
Lasercut panels

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/FortRebel#70]
1 each of
`Volty/drawings/module.svg`
`Triggy/drawings/module.svg`

and with engraving -
`drawings/blank4hp.svg`
`drawings/blank6hp.svg`

check that engraving comes through right and note optimal settings for next time

**Comment by pingdynasty** [comment]
any scrap perspex will do, pref 2mm

**Comment by padski** [comment]
Done
