### ISSUE TITLE
Biscuit schematic from reference design

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/FortRebel#76]
Create an Eagle schematic for the Biscuit smart socket based on the CRD5490 Reference Design.
http://www.cirrus.com/en/support/software/cs548x-9x.html

**Comment by pingdynasty** [comment]
Suggested CT is in the hardware proposal:
https://docs.google.com/spreadsheets/d/11r7iwuOsfJAZ1bjUkrsOAmda8crAknt1fsuqClWv4jk/edit#gid=0

**Comment by padski** [comment]
Done for prototype with Vigortronic supply. Saved copy with alt smps supply...
