### ISSUE TITLE
Pack and ship to Clockface

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/FortRebel#78]
2x Chronos
4x Stoicheia
2x Logoi
3x Klasmata

Clockface Modular
#803 Ritz Palacio

1-8-4
Hatagaya
Shibuya-ku
Tokyo 151-0072
Japan

todo: pack, get quote from DHL, update invoice, get payment, ship.

**Comment by padski** [comment]
Parcel dimensions: 30 x 31 x 35cm
Weight: estimate 2kg + tshirts

**Comment by pingdynasty** [comment]
done
