### ISSUE TITLE
Biscuit design: add PIR sensor

### ISSUE THREAD

**Issue by ghost** [RebelTechnology/FortRebel#81]
Part IRA-E700ST0.
Copy circuit from datasheet: Typical Application Circuit (Analog out Type), page 10.
Connect A_Out to Photon Analog in (any pin A0 to A6).

Datasheet:
http://www.murata.com/~/media/webrenewal/support/library/catalog/products/sensor/infrared/s21e.ashx

**Comment by padski** [comment]
done
