### ISSUE TITLE
Prepare order for Thonk

### ISSUE THREAD

**Issue by ghost** [RebelTechnology/FortRebel#82]
25 Logoi
25 Klasmata
50 Stoicheia

panel, pcb, mcu

@padski have we got enough panels?

**Comment by padski** [comment]
We have:
Logoi:
PCB - 4 x Rev05, 24 x Rev04, 100ish Rev03
Panel - 18

Klasmata:
PCB - 5 x Rev04, 31 x Rev03
Panel - ~70

Stoicheia:
PCB - 31 x Rev06, ~70 x Rev05
Panel - ~90

**Comment by pingdynasty** [comment]
Thonk order update:
100x Stoicheia
50x Logoi
50x Klasmata

**Comment by pingdynasty** [comment]
Plus:
5 x Stoicheia chips
3 x Logoi chips
3 x Klasmata chips

**Comment by pingdynasty** [comment]
Klasmata panels: apprx 12 remaining

**Comment by pingdynasty** [comment]
@padski todo: flash mcu's:
105 x Stoicheia
55 x Klasmata
55 x Logoi

**Comment by padski** [comment]
Done and boxed up
