### ISSUE TITLE
PSU for Tapco mixer

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/FortRebel#83]
Need a replacement PSU for the small Tapco MIX50 mixer.

Perhaps this one:
http://www.rapidonline.com/audio-visual/power-supply-psu3-35-5403/

will require replacement 3-pin plug (the Behringer mixers have female sockets, see
https://media.music-group.com/media/PLM/data/images/products/P0300/1800Wx1800H/UB1002FX_P0300_Rear_L.png)

or replacement socket.

todo: 
- find out if psu is compatible
- find suitable plug / socket
- add to shopping list
- figure out pin mapping

**Comment by padski** [comment]
Yes psu looks compatible, and found replacement socket to suit.
Both in Rebel shopping list

**Comment by pingdynasty** [comment]
done
