### ISSUE TITLE
Ship mcu's to George Meakin

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/FortRebel#84]
1x each of Stoicheia, Klasmata and Logoi MCU

plus a couple of OWL stickers and a product leaflet

ship to:
George Meakin
The Maples
Sweden Lane
Little Beckford
Tewkesbury
Gloucestershire
GL20 7AQ

**Comment by padski** [comment]
Ready to post

**Comment by padski** [comment]
Done
