### ISSUE TITLE
Make JTAG to SWD adaptor

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/FortRebel#88]
Make a small stripboard adaptor with 2x10 pin (boxed) male header for JTAG and 1x6 pin male header for SWD.

Connect pins:

```
JTAG   SWD DESCRIPTION
1-2      1 VAPP
3-6      3 GND
7        4 SWDIO
8        3 GND
9        2 SWCLK
10       3 GND
12       3 GND
13       6 SWO
14       3 GND
15       5 NRST
16       3 GND
18       3 GND
19       - VCC
20       3 GND
```

Add a jumper that optionally connects JTAG pin 19 VCC to JTAG pins 1-2 VAPP.

SWD pinout:

```
1 VCC
2 SWCLK
3 GND
4 SWDIO
5 NRST
6 SWO (optional)
```

JTAG pinout:
http://www.st.com/st-web-ui/static/active/en/resource/technical/document/user_manual/DM00026748.pdf

**Comment by pingdynasty** [comment]
Add a small pushbutton to short NRST to GND.

**Comment by padski** [comment]
Done
